-- MySQL Script generated by MySQL Workbench
-- Tue Mar 23 20:02:54 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema chati_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chati_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chati_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci ;
USE `chati_db` ;

-- -----------------------------------------------------
-- Table `chati_db`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chati_db`.`rol` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre_rol` TEXT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chati_db`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chati_db`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre_usuario` TEXT NULL,
  `correo_usuario` TEXT NULL,
  `clave_usuario` TEXT NULL,
  `genero_usuario` TINYINT NULL,
  `foto_usuario` TEXT NULL,
  `estado_usuario` TINYINT NULL,
  `activo_usuario` TINYINT NULL,
  `id_rol` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_usuario_rol1_idx` (`id_rol` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_rol1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `chati_db`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chati_db`.`amistad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chati_db`.`amistad` (
  `id_amistad` INT NOT NULL AUTO_INCREMENT,
  `estado_amistad` INT NULL,
  `id_solictante` INT NOT NULL,
  `id_solicitado` INT NOT NULL,
  PRIMARY KEY (`id_amistad`),
  INDEX `fk_usuario_has_usuario_usuario1_idx` (`id_solicitado` ASC) VISIBLE,
  INDEX `fk_usuario_has_usuario_usuario_idx` (`id_solictante` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_usuario_usuario`
    FOREIGN KEY (`id_solictante`)
    REFERENCES `chati_db`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_usuario_usuario1`
    FOREIGN KEY (`id_solicitado`)
    REFERENCES `chati_db`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chati_db`.`mensaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chati_db`.`mensaje` (
  `id_mensaje` INT NOT NULL AUTO_INCREMENT,
  `fecha_mensaje` TEXT NULL,
  `hora_mensaje` TEXT NULL,
  `estado_mensaje` TEXT NULL,
  `contenido_mensaje` TEXT NULL,
  `id_emisor` INT NOT NULL,
  `id_receptor` INT NOT NULL,
  PRIMARY KEY (`id_mensaje`),
  INDEX `fk_mensaje_usuario1_idx` (`id_emisor` ASC) VISIBLE,
  INDEX `fk_mensaje_usuario2_idx` (`id_receptor` ASC) VISIBLE,
  CONSTRAINT `fk_mensaje_usuario1`
    FOREIGN KEY (`id_emisor`)
    REFERENCES `chati_db`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mensaje_usuario2`
    FOREIGN KEY (`id_receptor`)
    REFERENCES `chati_db`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
